name: Go SDK

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main
    tags:
      - '*'

  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: -v --timeout 10m -E gofmt -E whitespace -E revive -E gosec -E goimports --skip-dirs='generated'

  go-test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - name: test code
        run: |
          go test -v ./...

  run-examples:
    name: Run examples (to look for regressions)
    runs-on: ubuntu-latest
    needs:
      - lint
      - go-tests
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - name: test examples (not rate limiting)
        run: |
          echo "Running smoke test"
          go run examples/smoke-test/smoke-test.go
          
          echo "Running screening test"
          go run examples/screening/screening.go  
  

  #FIXME: add integration test to confirm it is working with the most up to date bindings

  #FIXME: add job to release on tag
